### ISSUE TITLE
Verschiedene Hintergründe je nach Region

### ISSUE THREAD

**Issue by Kebap** [Kebap/krrrcks-mudlet#28]
Beispiel siehe http://forums.achaea.com/discussion/5067/wallpaper-with-gmcp-gif#latest?platform=hootsuite
Bilder auf Webseiten der Region

**Comment by krrrcks** [comment]
Hm, grundsätzlich nettes Feature. Aber vielleicht behalten wir das Hintergründe abhängig von X für noch andere mögliche sinnvolle Informationen? Ich finde, die Region ist außer "Stimmung" häufig nicht so entscheidend (es sei denn man muss wissen, welchem RM man eine E-Mail senden muss). Oder?

**Comment by Kebap** [comment]
Genau, der Hintergrund passt ja zur "Stimmung", mehr soll das nicht machen, eher ganz dezent, eben hintergründig. Ist mir jetzt nicht so dringend, aber für die Zukunft schön. 

Genau wie du schon sagst, sollten wir gleichzeitig auch darüber nachdenken, wie/wo wir weitere sinnvolle Informationen darzustellen können. Hierzu wäre erstmal #31 grundlegend: Wieviel Platz haben wir überhaupt neben dem laufenden Text?

**Comment by Kebap** [comment]
Zum Vergleich, die Farben der Regionen & co. in den News auf der MG Webseite:

```css
/* Regionstitel */
dt.mud { background-image: linear-gradient(90deg, #7FFF90 0%, rgba(0, 0, 0, 0) 90%); }  /* Quests, Gegenstaende, Aenderungen */
dt.gilde { background-image: linear-gradient(90deg, #FFFF88 0%, rgba(0, 0, 0, 0) 90%); }  /* Gilden */
dt.rl { background-image: linear-gradient(90deg, #88C0FF 0%, rgba(0, 0, 0, 0) 90%); }  /* RL, Menschen, Parties, Treffen */
dt.lib { background-image: linear-gradient(90deg, #FF90D0 0%, rgba(0, 0, 0, 0) 90%); } /* Mudlib, Crashes, Hierarchie, Global */

/* Regionstitelfarbverlaeufe */
.dschungel { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 70%, #6D7A45 90%);}
.ebene { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 65%, #00FB00 85%);}
.fernwest { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 70%, #C70025 90%);}
.gebirge { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 70%, #515650 90%);}
.inseln { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 70%, #0026FF 90%);}
.polar { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 65%, #C1FFFF 85%);}
.unterwelt { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 80%, #000000 98%);}
.vland { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 65%, #DAC520 85%);}
.wald { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 70%, #00770D 90%);}
.wueste { background-image: linear-gradient(30deg, rgba(0, 0, 0, 0) 65%, #D3AC4A 85%);}
```

edit: Hier im Vergleich nebeneinander:
![grafik](https://user-images.githubusercontent.com/117238/122042105-04addd80-cdda-11eb-8564-947de4f94085.png)

Siehe auch dieses praktische Tool, um zu einer Farbe passende Paletten zu berechnen: https://paletton.com
